name: 'Build and Deploy to Cloud Run'

on: workflow_dispatch
env:
  SERVICE_NAME: mascot-api

jobs:
  deploy:
    runs-on: 'ubuntu-latest'

    permissions:
      packages: read
      id-token: write

    steps:
    - name: Log into ghcr.io
      uses: docker/login-action@v3
      with:
        registry: ghcr.io
        username: ${{ github.actor }}
        password: ${{ secrets.GITHUB_TOKEN }}

    - name: Authenticate to Google Cloud
      id: auth
      uses: google-github-actions/auth@v2
      with:
        workload_identity_provider: ${{ secrets.GCP_WORKLOAD_IDENTITY_PROVIDER }}
        service_account: ${{ secrets.GCP_SERVICE_ACCOUNT }}
    
    - name: Set up Cloud SDK
      uses: 'google-github-actions/setup-gcloud@v2'

    - name: Configure Docker
      run: gcloud auth configure-docker us-central1-docker.pkg.dev

    - run: docker pull ghcr.io/digitaldegree/web-app-2:9a3e70cedf34149498354c1baee552e4057f324f
    - run: docker tag ghcr.io/digitaldegree/web-app-2:9a3e70cedf34149498354c1baee552e4057f324f us-central1-docker.pkg.dev/${{secrets.GCP_PROJECT_ID}}/web-app-2/${{env.SERVICE_NAME}}:9a3e70cedf34149498354c1baee552e4057f324f
    - run: docker image ls
    - run: docker push us-central1-docker.pkg.dev/${{secrets.GCP_PROJECT_ID}}/web-app-2/${{env.SERVICE_NAME}}:9a3e70cedf34149498354c1baee552e4057f324f
    - name: Deploy to Cloud Run
      uses: 'google-github-actions/deploy-cloudrun@v2'
      with:
        service: ${{ env.SERVICE_NAME }}
        region: us-central1
        image: us-central1-docker.pkg.dev/${{secrets.GCP_PROJECT_ID}}/web-app-2/${{env.SERVICE_NAME}}:9a3e70cedf34149498354c1baee552e4057f324f
        flags: '--allow-unauthenticated'

        