name: 'Build and Deploy to Cloud Run'

on: workflow_dispatch

jobs:
  deploy:
    runs-on: 'ubuntu-latest'

    permissions:
      packages: read

    steps:
    - name: Authenticate to Google Cloud
      id: auth
      uses: google-github-actions/auth@v2
      with:
        workload_identity_provider: ${{ secrets.GCP_WORKLOAD_IDENTITY_PROVIDER }}
        service_account: ${{ secrets.GCP_SERVICE_ACCOUNT }}
